# config/packages/web_profiler.yaml

framework:
  profiler:
    enabled: false
    collect: false
web_profiler:
  toolbar: false
  intercept_redirects: false


when@dev:
  framework:
    profiler:
      enabled: true
      collect: true
      only_exceptions: false
      collect_serializer_data: true
  web_profiler:
    toolbar: true
    intercept_redirects: false
